### ISSUE TITLE
Need Swagger API Documentation

### ISSUE THREAD

**Issue by ian-Liaozy** [CSCI-GA-2820-FA24-001/promotions#12]
**As a** developers
**I need** the Swagger API documentation
**So that** users and developers can easily understand how to use the API and what functionality it provides.
   
 ### Details and Assumptions
 * Swagger API documentation is generated for all CRUD endpoints.
 * Documentation includes request type, parameter details, request/response examples, and status codes.
 * The documentation is accessible at a dedicated URL (e.g., /api-docs).

 
 ### Acceptance Criteria  
   
 ```gherkin
 Given the Swagger API Documentation is created
 When I enter the documentation URL (e.g., /api-docs)
 Then I can see all the available API details in Swagger format
```

**Comment by raghavm1** [comment]
Solved by #43
