### ISSUE TITLE
Read a Promotion

### ISSUE THREAD

**Issue by wencfy** [CSCI-GA-2820-FA24-001/promotions#5]
As a system user
I need the ability to read a promotion
So that I can understand and evaluate the effectiveness of marketing campaigns

Details and Assumptions:

- We will retrieve the promotion details from a PostgreSQL database
- A promotion has the data schema as designed in #11 

Acceptance Criteria:

- Given there is at least one active promotion in the database
- When I read the details of a promotion, I should be able to see the name, description, start date, end date, and status of the promotion

**Comment by raghavm1** [comment]
completed by #16
