### ISSUE TITLE
R6: Continuous Deployment and Event Trigger Setup

### ISSUE THREAD

**Issue by yc6714** [CSCI-GA-2820-FA24-001/promotions#88]
**As a** DevOps engineer,
**I need** to set up an EventListener with a Trigger, TriggerBinding, and TriggerTemplate,
**So that** a PipelineRun is created automatically whenever a push is made to the master branch.
   
 ### Details and Assumptions
 * The EventListener setup will handle GitHub webhooks to start the pipeline.
 * Store these configurations in the .`tekton/` directory.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a push to the master branch
When the GitHub webhook is triggered
Then the Tekton pipeline should start executing automatically
```

**Comment by wencfy** [comment]
How did you tested this?

**Comment by pennyyang17** [comment]
I haven't yet, I think we would test the tekton pipeline as a whole once we add the pipeline.yaml, tasks.yaml, workspace.yaml files.

**Comment by pennyyang17** [comment]
> How did you tested this?

I haven't yet, I think we would test the tekton pipeline as a whole once we add the pipeline.yaml, tasks.yaml, workspace.yaml files.
